name: Test dp1s.sh

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Test dp1s.sh (${{ matrix.name }})
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run script
        run: bash dp1s.sh